'''
THE MODULES USE IN PYTHON OCCURS IN TWO MOMENTS:

FIRST MOMENT  
- GENERALISTIC, IMPORT ALL MODULES THE PACKAGE
    import from package_name

2 SECOUND MOMENT
- ESPECIFIC, IMPORT JUST MODULE IN USE
    from package_name import module_name


'''
