number = int(input('Enter a integer number: '))
print('{:*^20}'.format(' ADITION '))
print('{} + 1 = {}'.format(number, number+1))
print('{} + 2 = {}'.format(number, number+2))
print('{} + 3 = {}'.format(number, number+3))
print('{} + 4 = {}'.format(number, number+4))
print('{} + 5 = {}'.format(number, number+5))

print('{} + 6 = {}'.format(number, number+6))
print('{} + 7 = {}'.format(number, number+7))
print('{} + 8 = {}'.format(number, number+8))
print('{} + 9 = {}'.format(number, number+9))
print('{} + 10 = {}'.format(number, number+10))

print('{:*^20}'.format(' SUBTRACTION '))
print('{} - 1 = {}'.format(number, number-1))
print('{} - 2 = {}'.format(number, number-2))
print('{} - 3 = {}'.format(number, number-3))
print('{} - 4 = {}'.format(number, number-4))
print('{} - 5 = {}'.format(number, number-5))
print('{} - 6 = {}'.format(number, number-6))
print('{} - 7 = {}'.format(number, number-7))
print('{} - 8 = {}'.format(number, number-8))
print('{} - 9 = {}'.format(number, number-9))
print('{} - 10 = {}'.format(number, number-10))

print('{:*^20}'.format(' MULTIPLICATION '))
print('{} * 1 = {}'.format(number, number*1))
print('{} * 2 = {}'.format(number, number*2))
print('{} * 3 = {}'.format(number, number*3))
print('{} * 4 = {}'.format(number, number*4))
print('{} * 5 = {}'.format(number, number*5))
print('{} * 6 = {}'.format(number, number*6))
print('{} * 7 = {}'.format(number, number*7))
print('{} * 8 = {}'.format(number, number*8))
print('{} * 9 = {}'.format(number, number*9))
print('{} * 10 = {}'.format(number, number*10))

print('{:*^20}'.format(' DIVISION '))
print('{} / 1 = {:.2f}'.format(number, number/1))
print('{} / 2 = {:.2f}'.format(number, number/2))
print('{} / 3 = {:.2f}'.format(number, number/3))
print('{} / 4 = {:.2f}'.format(number, number/4))
print('{} / 5 = {:.2f}'.format(number, number/5))
print('{} / 6 = {:.2f}'.format(number, number/6))
print('{} / 7 = {:.2f}'.format(number, number/7))
print('{} / 8 = {:.2f}'.format(number, number/8))
print('{} / 9 = {:.2f}'.format(number, number/9))
print('{} / 10 = {:.2f}'.format(number, number/10))
